version: "3.9"
services:
  db:
    image: postgres:15.2
    #ports:
    #  - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub
    depends_on:
      - db

  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 512m
    ports:
      - 4444:4444
volumes:
  db-data:
  bundle: